### ISSUE TITLE
Auth Checklist

### ISSUE THREAD

**Issue by samwalker191** [jhnegbrt/sleuth#2]
# User Auth
## Functionality
- [x] The main button with logo should link to `/`
- [ ] Has working demo login
- [x] Smooth, bug free navigation
### Before Login
- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user
### After Login
- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in
## Style
- [ ] The site should look exactly like the actual site
- [ ] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production
## Seeds
- [x] Adequate and appropriate seeds

**Comment by jhnegbrt** [comment]
Hey Walker, I know there is still some CSS stuff on the splash page, but I have been going at that stuff for a while now and would like to come back to that and figure out how much time to spend on it once I get things going a little bit further. Plus, I feel like i have a pretty good start to the splash page  and anything else I would do is kind of extra

**Comment by samwalker191** [comment]
For sure, the splash page is good for now! 

You definitely have to go back and style the login/signup forms at some point. Im cool with moving on to the message MVP for now, and then come back and style the session forms after that one. 

I unchecked a few boxes that need to be looked at, so please refer to the checklist above for what needs to be fixed.

Regarding the 404 page, if you have a 404 page, then it needs styling as well. It would also need a button or some way for the user to get back to where they were before.
