### ISSUE TITLE
Live Messages Checklist

### ISSUE THREAD

**Issue by jhnegbrt** [jhnegbrt/sleuth#3]
# Live Messages

- [ ] Displays live messages 
- [ ] Users can edit their own messages && only their own
- [ ] Users can delete ther own messages && only ther own
- [ ] Only logged in users can access messages

## Styling

- [ ] Adequate overall styling
- [ ] Time is displayed only when message is from new sender, or more than 2 minutes have elapsed
- [ ] Delete and Edit functionality displayed on hover
- [ ] Displays username of message sender
- [ ] Aligns sender's messages right and other users' messages left
